(require 'ox-publish)
(setq org-latex-pdf-process '("pdflatex -interaction nonstopmode -output-directory %o %f" "bibtex %b" "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f" "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
(defun publish-html ()
  (interactive)
  (org-publish "blog" t)
  (shell-command "~/blog/public/countFiles.sh"))
(provide 'scripts)
